### PR TITLE
fix for checking running process

### PR DESCRIPTION
**Pull request by SpudGunMan**
dont forget to remove BETA label from menu :)

### CODE REVIEW

**Comment by SpudGunMan** [comment]
this is for vara modem checks

**Comment by km4ack** [comment]
are you getting a failure running this on a Pi? I am running it on 32bit Pi OS and not having an issue. Grep just for vara on the pi returns many results. `grep -i box86 | grep -i vara` only returns one result.

**Comment by SpudGunMan** [comment]
this is when I was working with raspberry-desktop-os more I just reloaded my dev pi's fresh now to test full load in again. I would assume this is not useable given it works for you I am testing in 64bit

**Comment by SpudGunMan** [comment]
aarm64 the problem of modem starting is an issue I will circle back and try this patch against my new pi4 build after finished bug hunting it

**Comment by km4ack** [comment]
Gotcha. Must be something specific to 64bit. BTW....reach out to me via email. mycall at arrl.net.

**Comment by SpudGunMan** [comment]
ok this is now closing for a better patch https://github.com/km4ack/patmenu2/pull/73

**Pull request closed without merging**
